name: Terraform Plan
on: push
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AZ_1A: ${{secrets.AZ_1A}}
  AZ_1B: ${{secrets.AZ_1B}}
  CIDR_BLOCK: ${{secrets.CIDR_BLOCK}}
  TF_VAR_AWS_KEY_PUB: ${{secrets.TF_VAR_AWS_KEY_PUB}}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Plan
      run: |
        terraform init
        terraform validate
        terraform plan
